name: DBMS
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - sqlite
  - pandas
  - openai
  - pip:
    - faiss-cpu
    - flask
    - flask-wtf
    - cerebrium
    - cohere
    - git-lfs  # Add Git LFS as a dependency

post-link:
  - git lfs install  # Run Git LFS installation after environment creation

git:
  lfs:
    track:
      - '*.csv'  # Track CSV files with Git LFS
