name: DBMS
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - sqlite
  - pandas
  - openai
  - faiss-cpu
  - flask
  - flask-wtf
  - flask-sqlalchemy
  - pip: 
    - cerebrium
    - cohere
