name: DBMS
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - sqlite
  - pandas
  - openai
  - pip:
    - faiss-cpu
    - flask
    - flask-wtf
    - cohere
    - git-lfs  # Add Git LFS as a dependency

